name: CI Pipeline

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install env
        uses: ./.github/actions/install-python-env

      - uses: extractions/setup-just@v2

      - name: Lint
        run: |
          source .venv/bin/activate
          just format --check
          just lint

      - name: Tests
        run: |
          source .venv/bin/activate
          pytest tests

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
